name: zl_test
description: ZL TEST
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.12.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  provider: ^6.1.5+1

dev_dependencies:
  build_runner: ^2.11.1
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
  fonts:
    - family: Italian Plate No2 Expanded
      fonts:
        - asset: assets/font/Italian Plate No2 Expanded Thin.ttf
          weight: 100
        - asset: assets/font/Italian Plate No2 Expanded Thin Italic.ttf
          weight: 100
          style: italic
        - asset: assets/font/Italian Plate No2 Expanded Ultralight.ttf
          weight: 200
        - asset: assets/font/Italian Plate No2 Expanded Ultralight Italic.ttf
          weight: 200
          style: italic
        - asset: assets/font/Italian Plate No2 Expanded Extralight.ttf
          weight: 200
        - asset: assets/font/Italian Plate No2 Expanded Extralight Italic.ttf
          weight: 200
          style: italic
        - asset: assets/font/Italian Plate No2 Expanded Light.ttf
          weight: 300
        - asset: assets/font/Italian Plate No2 Expanded Light Italic.ttf
          weight: 300
          style: italic
        - asset: assets/font/Italian Plate No2 Expanded.ttf
          weight: 400
        - asset: assets/font/Italian Plate No2 Expanded Italic.ttf
          weight: 400
          style: italic
        - asset: assets/font/Italian Plate No2 Expanded Medium.ttf
          weight: 500
        - asset: assets/font/Italian Plate No2 Expanded Medium Italic.ttf
          weight: 500
          style: italic
        - asset: assets/font/Italian Plate No2 Expanded Demibold.ttf
          weight: 600
        - asset: assets/font/Italian Plate No2 Expanded Demibold Italic.ttf
          weight: 600
          style: italic
        - asset: assets/font/Italian Plate No2 Expanded Bold.ttf
          weight: 700
        - asset: assets/font/Italian Plate No2 Expanded Bold Italic.ttf
          weight: 700
          style: italic
        - asset: assets/font/Italian Plate No2 Expanded Extrabold.ttf
          weight: 800
        - asset: assets/font/Italian Plate No2 Expanded Extrabold Italic.ttf
          weight: 800
          style: italic
        - asset: assets/font/Italian Plate No2 Expanded Black.ttf
          weight: 900
        - asset: assets/font/Italian Plate No2 Expanded Black Italic.ttf
          weight: 900
          style: italic

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    rive: false
    lottie: false
